version: 2

workflows:
  version: 2
  full_test:
    jobs:
      - npm-test

jobs:
  npm-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: npm test
          command: npm test
