name: Create Release Pull Request

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'The base branch for git operations and the pull request.'
        default: 'main'
        required: true
      release-type:
        description: 'A SemVer version diff, i.e. major, minor, or patch. Mutually exclusive with "release-version".'
        required: false
        type: choice
        options:
          - ''
          - major
          - minor
          - patch
      release-version:
        description: 'A specific version to bump to. Mutually exclusive with "release-type".'
        required: false

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false

          # This is to guarantee that the most recent tag is fetched. This can
          # be configured to a more reasonable value by consumers.
          fetch-depth: 0

          # We check out the specified branch, which will be used as the base
          # branch for all git operations and the release PR.
          ref: ${{ github.event.inputs.base-branch }}

      - uses: MetaMask/action-create-release-pr@v5
        with:
          release-type: ${{ github.event.inputs.release-type }}
          release-version: ${{ github.event.inputs.release-version }}
          formatter: 'oxfmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
