name: Main

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          persist-credentials: false
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash) 1.7.12
        shell: bash
      - name: Check workflow files
        env:
          ACTIONLINT_EXECUTABLE: ${{ steps.download-actionlint.outputs.executable }}
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          "$ACTIONLINT_EXECUTABLE" -color
        shell: bash

  analyse-code:
    name: Analyse code
    needs: check-workflows
    uses: MetaMask/action-security-code-scanner/.github/workflows/security-scan.yml@v2
    with:
      scanner-ref: v2
      paths-ignored: |
        .storybook/
        **/__snapshots__/
        **/*.snap
        **/*.stories.js
        **/*.stories.tsx
        **/*.test.browser.ts*
        **/*.test.js*
        **/*.test.ts*
        **/fixtures/
        **/jest.config.js
        **/jest.environment.js
        **/mocks/
        **/test*/
        docs/
        e2e/
        merged-packages/
        node_modules/
        storybook/
        test*/
    secrets:
      project-metrics-token: ${{ secrets.SECURITY_SCAN_METRICS_TOKEN }}
      slack-webhook: ${{ secrets.APPSEC_BOT_SLACK_WEBHOOK }}
    permissions:
      actions: read
      contents: read
      security-events: write

  build-lint-test:
    name: Build, lint, and test
    uses: ./.github/workflows/build-lint-test.yml

  all-jobs-completed:
    name: All jobs completed
    runs-on: ubuntu-latest
    needs:
      - check-workflows
      - analyse-code
      - build-lint-test
    permissions: {}
    outputs:
      PASSED: ${{ steps.set-output.outputs.PASSED }}
    steps:
      - name: Set PASSED output
        id: set-output
        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"

  all-jobs-pass:
    name: All jobs pass
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: all-jobs-completed
    permissions: {}
    steps:
      - name: Check that all jobs have passed
        env:
          PASSED: ${{ needs.all-jobs-completed.outputs.PASSED }}
        run: |
          if [[ $PASSED != "true" ]]; then
            exit 1
          fi

  is-release:
    # Filtering by `push` events ensures that we only release from the `main` branch, which is a
    # requirement for our npm publishing environment.
    # The commit author should always be 'github-actions' for releases created by the
    # 'create-release-pr' workflow, so we filter by that as well to prevent accidentally
    # triggering a release.
    if: github.event_name == 'push' && startsWith(github.event.head_commit.author.name, 'github-actions')
    needs: all-jobs-pass
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/action-is-release@v2
        id: is-release

  publish-release:
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    name: Publish release
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
