name: Publish docs to GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string

jobs:
  publish-docs-to-gh-pages:
    name: Publish docs to GitHub Pages
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Ensure `destination_dir` is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - name: Get access token
        id: get-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            contents: write
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false
      - name: Run build script
        run: yarn build:docs
      - name: Deploy to `${{ inputs.destination_dir }}` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935
        with:
          personal_token: ${{ steps.get-token.outputs.token }}
          publish_dir: ./docs
          destination_dir: ${{ inputs.destination_dir }}
