name: Publish Release

on:
  push:
    branches: [main]

jobs:
  is-release:
    # release merge commits come from github-actions
    if: startsWith(github.event.commits[0].author.name, 'github-actions')
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    runs-on: ubuntu-latest
    steps:
      - uses: MetaMask/action-is-release@v1
        id: is-release

  publish-release:
    permissions:
      contents: write
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    runs-on: ubuntu-latest
    needs: is-release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - uses: MetaMask/action-publish-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run: |
          yarn install
          yarn build
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./dist
          key: ${{ github.sha }}

  publish-npm-dry-run:
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./dist
          key: ${{ github.sha }}
      - name: Dry Run Publish
        uses: MetaMask/action-npm-publish@v6
        with:
          dry-run: true
        env:
          SKIP_PREPACK: true

  publish-npm:
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./dist
          key: ${{ github.sha }}
      - name: Publish
        uses: MetaMask/action-npm-publish@v6
        with:
          dry-run: false
          # This `NPM_TOKEN` is only needed to publish a package for the first
          # time. Look in the repository settings under "Environments", and set
          # this token in the `npm-publish` environment, then delete it after
          # the initial OIDC publish.
          npm-token: ${{ secrets.NPM_TOKEN }}
        env:
          SKIP_PREPACK: true

  get-release-version:
    runs-on: ubuntu-latest
    needs: publish-npm
    outputs:
      RELEASE_VERSION: ${{ steps.get-release-version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - id: get-release-version
        shell: bash
        run: ./scripts/get.sh ".version" "RELEASE_VERSION"

  publish-release-to-gh-pages:
    needs: get-release-version
    name: Publish docs to `${{ needs.get-release-version.outputs.RELEASE_VERSION }}` directory of `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-docs.yml
    with:
      destination_dir: ${{ needs.get-release-version.outputs.RELEASE_VERSION }}

  publish-release-to-latest-gh-pages:
    needs: publish-npm
    name: Publish docs to `latest` directory of `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-docs.yml
    with:
      destination_dir: latest
